spring:
  application:
    name: service-list
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848


















#spring:
#  application:
#    name: service-list
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.128:8848











#spring:
#  application:
#    name: service-list
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.128:8848
